name: publish

on:
  # Triggers the workflow on push or pull request events but only for
  # the master branch
  push:
    branches: [ master ]
    paths:
      - config.org
      - assets/html-export.setup

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "publish"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 27.2

      # I don't know if the runner has anything configured that uses
      # the XDG directory layout, so is better to guarantee the
      # ~/.config exists
      - name: Prepare home config
        run: mkdir -p ~/.config

      - name: Clone Doom
        run: git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.config/emacs

      # This installation is simply to cache Doom packages
      - name: Installing Doom Emacs
        run: ~/.config/emacs/bin/doom install --no-config --no-env --no-fonts

      - name: Clone my private config
        run: git clone --depth 1 https://github.com/Townk/doom-emacs-private ~/.config/doom

      - name: Install PlantUML jar
        run: curl -sSfL https://sourceforge.net/projects/plantuml/files/plantuml.jar/download -o /tmp/plantuml.jar

      # This step is required to make sure any package I installed
      # extra gets installed. Also it removes packages I don't use
      # - name: Synchronizing private config with Doom
      #   run: ~/.config/emacs/bin/doom sync

      # This command tries to simulate the normal Emacs startup before
      # tangling the config file
      - name: Export config.org to HTML
        run: ~/.config/doom/.github/support/scripts/publish.sh

      - name: Checkout private config
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      # This step, besides committing the tangled file to the gh-pages
      # branch, it also fetches the setup file from the master branch
      # and commit it to the gh-pages branch in order to allow others
      # to use it by including the github.io address
      - name: Publish GitHub Page
        run: |
          cp ~/.config/doom/config.html index.html
          cp -R ~/.config/doom/assets/* assets/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git fetch origin master
          git commit -m "Auto-tangled from $GITHUB_SHA"
          git push
