name: publish

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Emacs
        uses: purcell/setup-emacs@master
        with:
          version: 27.2

      - name: Clone Doom
        run: git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d

      - name: Clone my private config
        run: |
          mkdir -p ~/.config
          git clone --depth 1 https://github.com/Townk/doom-emacs-private ~/.config/doom

      - name: Installing Doom Emacs
        run: ~/.emacs.d/bin/doom install --no-env --no-fonts

      - name: Tangle config file
        run: |
          cd ~/.config/doom
          emacs --batch --eval "(require 'org)" --eval '(progn (setq org-confirm-babel-evaluate nil) (org-babel-tangle-file "config.org"))'

      - name: Checkout private config
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp ~/.config/doom/config.html index.html
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Auto-tangled from $GITHUB_SHA"
          git push
